/**
 * 
 */
package cn.strong.fastdfs.client;

/**
 * Fastdfs 用到的命令代码
 * 
 * @author liulongbiao
 *
 */
public interface CommandCodes {

	byte FDFS_PROTO_CMD_QUIT = 82;
	byte FDFS_PROTO_CMD_RESP = 100;

	byte TRACKER_PROTO_CMD_SERVER_LIST_GROUP = 91;
	byte TRACKER_PROTO_CMD_SERVER_LIST_STORAGE = 92;
	byte TRACKER_PROTO_CMD_SERVER_DELETE_STORAGE = 93;

	byte TRACKER_PROTO_CMD_SERVICE_QUERY_STORE_WITHOUT_GROUP_ONE = 101;
	byte TRACKER_PROTO_CMD_SERVICE_QUERY_FETCH_ONE = 102;
	byte TRACKER_PROTO_CMD_SERVICE_QUERY_UPDATE = 103;
	byte TRACKER_PROTO_CMD_SERVICE_QUERY_STORE_WITH_GROUP_ONE = 104;
	byte TRACKER_PROTO_CMD_SERVICE_QUERY_FETCH_ALL = 105;
	byte TRACKER_PROTO_CMD_SERVICE_QUERY_STORE_WITHOUT_GROUP_ALL = 106;
	byte TRACKER_PROTO_CMD_SERVICE_QUERY_STORE_WITH_GROUP_ALL = 107;

	byte FDFS_PROTO_CMD_ACTIVE_TEST = 111;

	byte STORAGE_PROTO_CMD_UPLOAD_FILE = 11;
	byte STORAGE_PROTO_CMD_DELETE_FILE = 12;
	byte STORAGE_PROTO_CMD_SET_METADATA = 13;
	byte STORAGE_PROTO_CMD_DOWNLOAD_FILE = 14;
	byte STORAGE_PROTO_CMD_GET_METADATA = 15;
	byte STORAGE_PROTO_CMD_UPLOAD_SLAVE_FILE = 21;
	byte STORAGE_PROTO_CMD_QUERY_FILE_INFO = 22;
	byte STORAGE_PROTO_CMD_UPLOAD_APPENDER_FILE = 23; // create appender file
	byte STORAGE_PROTO_CMD_APPEND_FILE = 24; // append file
	byte STORAGE_PROTO_CMD_MODIFY_FILE = 34; // modify appender file
	byte STORAGE_PROTO_CMD_TRUNCATE_FILE = 36; // truncate appender file
}
